website/Solidare-IT-g6/config/routes.rb
SolidareItG6::Application.routes.draw do
  devise_for :users
  resources :users

  root 'index#home'

  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "create_account", :to =>"devise/registrations#new"
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

website/Solidare-IT-g6/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :presence => true
  validates :firstname, :presence => true
  validates :birthdate, :presence => true,:date => { :before => Time.now }
  validates :email, :presence => true,:format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create }
  validates :karma, :presence => true ,:numericality => :only_integer


  def all_name
    "#{firstname} #{name}"
  end

end

website/Solidare-IT-g6/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

website/Solidare-IT-g6/app/controllers/index_controller.rb
class IndexController < ApplicationController

  def home
  end
end

website/Solidare-IT-g6/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :firstname, :birthdate, :email, :karma, :id_ok, :presentation, :inscription_ok)
    end
end

website/Solidare-IT-g6/app/helpers/application_helper.rb
module ApplicationHelper
end

website/Solidare-IT-g6/app/helpers/index_helper.rb
module IndexHelper
end

website/Solidare-IT-g6/app/helpers/users_helper.rb
module UsersHelper
end

website/Solidare-IT-g6/app/views/index/home.html.erb
This is the home page!!!

website/Solidare-IT-g6/app/views/layouts/_usermenu.html.erb
<%if user_signed_in? %>
                                                <li><%=  current_user.all_name %></li>
                                                <li class="divider-vertical"></li>
                                                <li class="dropdown">
                                                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= image_tag "profil.jpg", :class=>'img-circle' %><b class="caret"></b></a>
                                                  <ul class="dropdown-menu">
                                                      <li class="nav-header">Personnal</li>
                                                    <li><%= link_to "Modif my account",  edit_user_registration_path(current_user) %></li>
                                                    <li><%= link_to "Modif my profil",  edit_user_path(current_user) %></li>
                                                    
                                                      <li class="divider"></li>
                                                    <li><%= link_to "Sign out",  destroy_user_session_path %></li>
                                                  </ul>
                                                </li>
                                              <% else %>
                                                <li><a href="/sign_in">Sign in</a></li>
                                              <% end %>

website/Solidare-IT-g6/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SolidareItG6</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
        <div id="header" class="hero-unit">
            <div style="text-align: center;"><img src="/images/logo.png" alt ="logo" align="center"></img></div>
            <h1>Solidare-it</h1>
            <p>Un site solidaire!</p>
                                        <% location= request.env['PATH_INFO'] %>
                                        <div class="navbar">
                                          <div class="navbar-inner">

                                            <ul class="nav">
                                               <% if location=='/' %>
                                                <li class="active">
                                              <% else %>
                                                <li>
                                              <% end %>
                                                <a href="<%= root_path  %>">Home</a></li>
                                              
                                            </ul>
                                             <ul class="nav pull-right">
                                                <%= render 'layouts/usermenu' %>
                                            </ul>
                                          </div>
                                        </div>


          </div>

  
  


<%= yield %>
  </div>

</body>
</html>

website/Solidare-IT-g6/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br>
    <%= f.datetime_select :birthdate %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :karma %><br>
    <%= f.text_field :karma %>
  </div>
  <div class="field">
    <%= f.label :id_ok %><br>
    <%= f.check_box :id_ok %>
  </div>
  <div class="field">
    <%= f.label :presentation %><br>
    <%= f.text_area :presentation %>
  </div>
  <div class="field">
    <%= f.label :inscription_ok %><br>
    <%= f.check_box :inscription_ok %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

website/Solidare-IT-g6/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

website/Solidare-IT-g6/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Firstname</th>
      <th>Birthdate</th>
      <th>Email</th>
      <th>Karma</th>
      <th>Id ok</th>
      <th>Presentation</th>
      <th>Inscription ok</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.firstname %></td>
        <td><%= user.birthdate %></td>
        <td><%= user.email %></td>
        <td><%= user.karma %></td>
        <td><%= user.id_ok %></td>
        <td><%= user.presentation %></td>
        <td><%= user.inscription_ok %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

website/Solidare-IT-g6/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

website/Solidare-IT-g6/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @user.birthdate %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Karma:</strong>
  <%= @user.karma %>
</p>

<p>
  <strong>Id ok:</strong>
  <%= @user.id_ok %>
</p>

<p>
  <strong>Presentation:</strong>
  <%= @user.presentation %>
</p>

<p>
  <strong>Inscription ok:</strong>
  <%= @user.inscription_ok %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>